'use client';

import * as React from 'react';
import { Contrato } from '@/types/contrato';
import { Proposta } from '@/types/proposta';
import { Badge } from '@/components/ui/badge-2';
import { format } from 'date-fns';
import { ptBR } from 'date-fns/locale';
import { Plus, Edit, Search, Check, Trash2, ChevronDown, ExternalLink, Copy, AlertCircle } from 'lucide-react';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { Spinner } from '@/components/ui/spinner';
import { supabase, type ContratoUpdate, type ContratoInsert } from '@/lib/supabase';
import { useToast } from '@/components/ui/toast-1';
import { mockPropostas } from '@/data/mock-propostas';
import { mockContratos } from '@/data/mock-contratos';
import { createSlug, isValidSlug } from '@/utils/slug';

const STATUS_LABELS: Record<Contrato['status'], string> = {
  rascunho: 'Rascunho',
  ativo: 'Ativo',
  concluido: 'Concluído',
  cancelado: 'Cancelado',
};

const STATUS_COLORS: Record<Contrato['status'], 'secondary' | 'warning' | 'success' | 'destructive'> = {
  rascunho: 'secondary',
  ativo: 'warning',
  concluido: 'success',
  cancelado: 'destructive',
};

const isUuid = (value: string) =>
  /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value);

export default function ContratosTable() {
  const { showToast } = useToast();
  const [contratos, setContratos] = React.useState<Contrato[]>([]);
  const [isModalOpen, setIsModalOpen] = React.useState(false);
  const [isDeleteDialogOpen, setIsDeleteDialogOpen] = React.useState(false);
  const [contratoToDelete, setContratoToDelete] = React.useState<Contrato | null>(null);
  const [selectedContrato, setSelectedContrato] = React.useState<Contrato | null>(null);
  const [isEditing, setIsEditing] = React.useState(false);
  const [searchQuery, setSearchQuery] = React.useState('');
  const [isLoading, setIsLoading] = React.useState(true);
  const [isSaving, setIsSaving] = React.useState(false);
  const [isDeleting, setIsDeleting] = React.useState(false);
  const [hasChanges, setHasChanges] = React.useState(false);
  const [originalContrato, setOriginalContrato] = React.useState<Contrato | null>(null);
  const [propostas, setPropostas] = React.useState<Proposta[]>([]);
  const [autocompleteQuery, setAutocompleteQuery] = React.useState('');
  const [showAutocomplete, setShowAutocomplete] = React.useState(false);
  const [slugWasAutoGenerated, setSlugWasAutoGenerated] = React.useState(false);
  const autocompleteRef = React.useRef<HTMLDivElement>(null);
  const [isRemoveSignatureDialogOpen, setIsRemoveSignatureDialogOpen] = React.useState(false);
  const [signatureToRemove, setSignatureToRemove] = React.useState<'noiva' | 'noivo' | null>(null);
  const [isRemovingSignature, setIsRemovingSignature] = React.useState(false);

  // Carregar contratos do Supabase (fallback para mock se não configurado)
  React.useEffect(() => {
    let cancelled = false;

    const load = async () => {
      try {
        if (!supabase) {
          if (!cancelled) {
            setContratos(mockContratos);
            setIsLoading(false);
          }
          return;
        }

        const { data, error } = await (supabase as any)
          .from('contratos')
          .select('id, titulo, slug, descricao, valor_total, status, data_assinatura, data_evento, data_contrato, local_festa, numero_convidados, nome_noiva, cpf_noiva, nome_noivo, cpf_noivo, endereco, assinatura_noiva, assinatura_noivo, created_at')
          .order('created_at', { ascending: false });

        if (error) throw error;

        const mapped: Contrato[] = (data || []).map((row: any) => {
          // Processar assinaturas
          let assinaturaNoiva = row.assinatura_noiva;
          let assinaturaNoivo = row.assinatura_noivo;
          
          // Processar assinatura da noiva
          if (assinaturaNoiva) {
            try {
              if (typeof assinaturaNoiva === 'string' && assinaturaNoiva.startsWith('{')) {
                assinaturaNoiva = JSON.parse(assinaturaNoiva).base64;
              }
              if (assinaturaNoiva && !assinaturaNoiva.startsWith('data:')) {
                assinaturaNoiva = `data:image/png;base64,${assinaturaNoiva}`;
              }
            } catch (e) {
              console.error('Erro ao processar assinatura noiva:', e);
            }
          }
          
          // Processar assinatura do noivo
          if (assinaturaNoivo) {
            try {
              if (typeof assinaturaNoivo === 'string' && assinaturaNoivo.startsWith('{')) {
                assinaturaNoivo = JSON.parse(assinaturaNoivo).base64;
              }
              if (assinaturaNoivo && !assinaturaNoivo.startsWith('data:')) {
                assinaturaNoivo = `data:image/png;base64,${assinaturaNoivo}`;
              }
            } catch (e) {
              console.error('Erro ao processar assinatura noivo:', e);
            }
          }
          
          return ({
          id: String(row.id),
          clienteNome: String(row.titulo ?? ''),
          valorTotal: Number(row.valor_total ?? 0),
          status: row.status || 'rascunho',
          dataCriacao: String(row.created_at ?? new Date().toISOString()),
          dataEvento: row.data_evento ? `${row.data_evento}T00:00:00` : '',
          dataContrato: row.data_contrato ? `${row.data_contrato}T00:00:00` : undefined,
          descricao: row.descricao ?? undefined,
          slug: row.slug ?? undefined,
          localFesta: row.local_festa ?? undefined,
          numeroConvidados: row.numero_convidados ?? undefined,
          nomeNoiva: row.nome_noiva ?? undefined,
          cpfNoiva: row.cpf_noiva ?? undefined,
          nomeNoivo: row.nome_noivo ?? undefined,
          cpfNoivo: row.cpf_noivo ?? undefined,
          endereco: row.endereco ?? undefined,
          assinaturaNoiva: assinaturaNoiva ?? undefined,
          assinaturaNoivo: assinaturaNoivo ?? undefined,
        });
        });

        if (!cancelled) {
          setContratos(mapped);
          setIsLoading(false);
        }
      } catch (err) {
        console.error('Erro ao carregar contratos:', err);
        if (!cancelled) {
          setContratos(mockContratos);
          setIsLoading(false);
          showToast('Não foi possível carregar do Supabase (usando dados locais).', 'warning');
        }
      }
    };

    load();
    return () => {
      cancelled = true;
    };
  }, [showToast]);

  // Carregar propostas do Supabase para autocomplete
  React.useEffect(() => {
    let cancelled = false;

    const loadPropostas = async () => {
      try {
        if (!supabase) {
          // Usar mock se Supabase não estiver configurado
          if (!cancelled) {
            setPropostas(mockPropostas);
          }
          return;
        }

        const { data, error } = await (supabase as any)
          .from('propostas')
          .select('id, titulo, valor_total, validade_ate, local_festa, numero_convidados, descricao')
          .order('created_at', { ascending: false });

        if (error) throw error;

        const mapped: Proposta[] = (data || []).map((row: any) => ({
          id: String(row.id),
          clienteNome: String(row.titulo ?? ''),
          valorTotal: Number(row.valor_total ?? 0),
          status: 'enviada' as const,
          dataCriacao: new Date().toISOString(),
          dataEvento: row.validade_ate ? `${row.validade_ate}T00:00:00` : '',
          localFesta: row.local_festa ?? undefined,
          numeroConvidados: row.numero_convidados ?? undefined,
          descricao: row.descricao ?? undefined,
          itens: [],
        }));

        if (!cancelled) {
          setPropostas(mapped);
        }
      } catch (err) {
        console.error('Erro ao carregar propostas:', err);
        // Fallback para mock em caso de erro
        if (!cancelled) {
          setPropostas(mockPropostas);
        }
      }
    };

    loadPropostas();
    return () => {
      cancelled = true;
    };
  }, []);

  // Fechar autocomplete ao clicar fora
  React.useEffect(() => {
    const handleClickOutside = (event: MouseEvent) => {
      if (autocompleteRef.current && !autocompleteRef.current.contains(event.target as Node)) {
        setShowAutocomplete(false);
      }
    };

    document.addEventListener('mousedown', handleClickOutside);
    return () => {
      document.removeEventListener('mousedown', handleClickOutside);
    };
  }, []);

  // Detectar mudanças comparando contrato atual com original
  React.useEffect(() => {
    if (!selectedContrato || !originalContrato) {
      setHasChanges(false);
      return;
    }

    const changed = JSON.stringify(selectedContrato) !== JSON.stringify(originalContrato);
    setHasChanges(changed);
  }, [selectedContrato, originalContrato]);

  const handleAddContrato = () => {
    const newContrato: Contrato = {
      id: `new-${Date.now()}`,
      clienteNome: '',
      valorTotal: 0,
      status: 'rascunho',
      dataCriacao: new Date().toISOString(),
      dataEvento: '',
      descricao: '',
      slug: '',
    };
    setSelectedContrato(newContrato);
    setOriginalContrato(null);
    setHasChanges(false);
    setIsEditing(true);
    setAutocompleteQuery('');
    setShowAutocomplete(false);
    setSlugWasAutoGenerated(false);
    setIsModalOpen(true);
  };

  const handleSelectProposta = (proposta: Proposta) => {
    if (!selectedContrato) return;

    // Gerar slug baseado no nome da proposta
    const autoSlug = createSlug(proposta.clienteNome);

    setSelectedContrato({
      ...selectedContrato,
      clienteNome: proposta.clienteNome,
      dataEvento: proposta.dataEvento,
      localFesta: proposta.localFesta,
      valorTotal: proposta.valorTotal,
      numeroConvidados: proposta.numeroConvidados,
      descricao: proposta.descricao,
      slug: autoSlug,
    });
    setAutocompleteQuery(proposta.clienteNome);
    setShowAutocomplete(false);
  };

  const handleEditContrato = (contrato: Contrato) => {
    setSelectedContrato(contrato);
    setOriginalContrato(JSON.parse(JSON.stringify(contrato)));
    setHasChanges(false);
    setIsEditing(true);
    setAutocompleteQuery(contrato.clienteNome);
    setShowAutocomplete(false);
    setSlugWasAutoGenerated(false);
    setIsModalOpen(true);
  };

  const handleSaveContrato = async () => {
    if (!selectedContrato) return;

    if (!selectedContrato.clienteNome.trim()) {
      showToast('Informe o nome dos noivos.', 'warning');
      return;
    }

    // Validar slug se fornecido
    if (selectedContrato.slug && !isValidSlug(selectedContrato.slug)) {
      showToast('URL inválida. Use apenas letras minúsculas, números e hífens.', 'warning');
      return;
    }

    const isNewContrato = selectedContrato.id.startsWith('new-');

    // Gerar slug automaticamente se não fornecido
    let slug = selectedContrato.slug?.trim() || createSlug(selectedContrato.clienteNome);

    // Fallback: sem Supabase configurado, mantém comportamento local
    if (!supabase) {
      if (isNewContrato) {
        const newId = `local-${Date.now()}`;
        const newContrato = { ...selectedContrato, id: newId, slug };
        setContratos([...contratos, newContrato]);
      } else {
        setContratos(contratos.map((c) => (c.id === selectedContrato.id ? { ...selectedContrato, slug } : c)));
      }
      setIsModalOpen(false);
      setSelectedContrato(null);
      showToast('Contrato salvo localmente (Supabase não configurado).', 'warning');
      return;
    }

    setIsSaving(true);
    try {
      if (isNewContrato) {
        // Criar novo contrato - precisa de lead_id e numero_contrato
        const { data: leads, error: leadsError } = await (supabase as any)
          .from('leads')
          .select('id')
          .limit(1);

        if (leadsError || !leads || leads.length === 0) {
          showToast('É necessário ter pelo menos um lead cadastrado para criar um contrato.', 'error');
          setIsSaving(false);
          return;
        }

        // Gerar número do contrato (timestamp simplificado)
        const numeroContrato = `CONT-${Date.now()}`;
        const hoje = new Date().toISOString().split('T')[0];

        const payload: ContratoInsert = {
          lead_id: leads[0].id,
          numero_contrato: numeroContrato,
          titulo: selectedContrato.clienteNome.trim(),
          slug: slug || null,
          descricao: selectedContrato.descricao?.trim() || null,
          valor_total: selectedContrato.valorTotal,
          valor_pago: 0,
          valor_pendente: selectedContrato.valorTotal,
          status: selectedContrato.status,
          data_assinatura: hoje,
          data_inicio: hoje,
          data_entrega: selectedContrato.dataEvento ? selectedContrato.dataEvento.split('T')[0] : hoje,
          data_evento: selectedContrato.dataEvento ? selectedContrato.dataEvento.split('T')[0] : null,
          data_contrato: selectedContrato.dataContrato ? selectedContrato.dataContrato.split('T')[0] : null,
          local_festa: selectedContrato.localFesta?.trim() || null,
          numero_convidados: selectedContrato.numeroConvidados ?? null,
          nome_noiva: selectedContrato.nomeNoiva?.trim() || null,
          cpf_noiva: selectedContrato.cpfNoiva?.trim() || null,
          nome_noivo: selectedContrato.nomeNoivo?.trim() || null,
          cpf_noivo: selectedContrato.cpfNoivo?.trim() || null,
          endereco: selectedContrato.endereco?.trim() || null,
        } as any;

        const { data, error } = await (supabase as any)
          .from('contratos')
          .insert(payload)
          .select('id, titulo, slug, descricao, valor_total, status, data_assinatura, data_evento, data_contrato, local_festa, numero_convidados, nome_noiva, cpf_noiva, nome_noivo, cpf_noivo, endereco, created_at')
          .single();

        if (error) throw error;

        const newContrato: Contrato = {
          id: String(data.id),
          clienteNome: String(data.titulo ?? ''),
          valorTotal: Number(data.valor_total ?? 0),
          status: data.status || 'rascunho',
          dataCriacao: String(data.created_at ?? new Date().toISOString()),
          dataEvento: data.data_evento ? `${data.data_evento}T00:00:00` : '',
          dataContrato: data.data_contrato ? `${data.data_contrato}T00:00:00` : undefined,
          descricao: data.descricao ?? undefined,
          slug: data.slug ?? undefined,
          localFesta: data.local_festa ?? undefined,
          numeroConvidados: data.numero_convidados ?? undefined,
          nomeNoiva: data.nome_noiva ?? undefined,
          cpfNoiva: data.cpf_noiva ?? undefined,
          nomeNoivo: data.nome_noivo ?? undefined,
          cpfNoivo: data.cpf_noivo ?? undefined,
          endereco: data.endereco ?? undefined,
        };

        setContratos((prev) => [newContrato, ...prev]);
        setIsModalOpen(false);
        setSelectedContrato(null);
        setHasChanges(false);
        setOriginalContrato(null);
        showToast('Contrato criado com sucesso!', 'success');
      } else {
        // Atualizar contrato existente
        const payload: ContratoUpdate = {
          titulo: selectedContrato.clienteNome.trim(),
          slug: slug || null,
          descricao: selectedContrato.descricao?.trim() || null,
          valor_total: selectedContrato.valorTotal,
          valor_pendente: selectedContrato.valorTotal, // Atualizar conforme necessário
          status: selectedContrato.status,
          data_evento: selectedContrato.dataEvento ? selectedContrato.dataEvento.split('T')[0] : null,
          data_contrato: selectedContrato.dataContrato ? selectedContrato.dataContrato.split('T')[0] : null,
          data_entrega: selectedContrato.dataEvento ? selectedContrato.dataEvento.split('T')[0] : undefined,
          local_festa: selectedContrato.localFesta?.trim() || null,
          numero_convidados: selectedContrato.numeroConvidados ?? null,
          nome_noiva: selectedContrato.nomeNoiva?.trim() || null,
          cpf_noiva: selectedContrato.cpfNoiva?.trim() || null,
          nome_noivo: selectedContrato.nomeNoivo?.trim() || null,
          cpf_noivo: selectedContrato.cpfNoivo?.trim() || null,
          endereco: selectedContrato.endereco?.trim() || null,
        } as any;

        const { data, error } = await (supabase as any)
          .from('contratos')
          .update(payload)
          .eq('id', selectedContrato.id)
          .select('id, titulo, slug, descricao, valor_total, status, data_assinatura, data_evento, data_contrato, local_festa, numero_convidados, nome_noiva, cpf_noiva, nome_noivo, cpf_noivo, endereco, created_at')
          .single();

        if (error) throw error;

        const updated: Contrato = {
          id: String(data.id),
          clienteNome: String(data.titulo ?? ''),
          valorTotal: Number(data.valor_total ?? 0),
          status: data.status || 'rascunho',
          dataCriacao: String(data.created_at ?? selectedContrato.dataCriacao),
          dataEvento: data.data_evento ? `${data.data_evento}T00:00:00` : '',
          dataContrato: data.data_contrato ? `${data.data_contrato}T00:00:00` : undefined,
          descricao: data.descricao ?? undefined,
          slug: data.slug ?? undefined,
          localFesta: data.local_festa ?? undefined,
          numeroConvidados: data.numero_convidados ?? undefined,
          nomeNoiva: data.nome_noiva ?? undefined,
          cpfNoiva: data.cpf_noiva ?? undefined,
          nomeNoivo: data.nome_noivo ?? undefined,
          cpfNoivo: data.cpf_noivo ?? undefined,
          endereco: data.endereco ?? undefined,
        };

        setContratos((prev) => prev.map((c) => (c.id === updated.id ? updated : c)));
        setIsModalOpen(false);
        setSelectedContrato(null);
        setHasChanges(false);
        setOriginalContrato(null);
        showToast('Contrato atualizado com sucesso!', 'success');
      }
    } catch (err) {
      console.error('Erro ao salvar contrato:', err);
      showToast('Erro ao salvar contrato.', 'error');
    } finally {
      setIsSaving(false);
    }
  };

  const handleCloseModal = () => {
    setIsModalOpen(false);
    setTimeout(() => {
      setSelectedContrato(null);
      setIsEditing(false);
      setHasChanges(false);
      setOriginalContrato(null);
      setAutocompleteQuery('');
      setShowAutocomplete(false);
    }, 200);
  };

  const handleDeleteClick = (contrato: Contrato) => {
    setContratoToDelete(contrato);
    setIsDeleteDialogOpen(true);
  };

  const handleConfirmDelete = async () => {
    if (!contratoToDelete) return;

    // Fallback: sem Supabase configurado, mantém comportamento local
    if (!supabase) {
      setContratos((prev) => prev.filter((c) => c.id !== contratoToDelete.id));
      showToast('Contrato excluído localmente (Supabase não configurado).', 'warning');
      setIsDeleteDialogOpen(false);
      setContratoToDelete(null);
      setIsModalOpen(false);
      setSelectedContrato(null);
      return;
    }

    setIsDeleting(true);
    try {
      const { error } = await (supabase as any)
        .from('contratos')
        .delete()
        .eq('id', contratoToDelete.id);

      if (error) throw error;

      setContratos((prev) => prev.filter((c) => c.id !== contratoToDelete.id));
      showToast('Contrato excluído com sucesso!', 'success');
      setIsDeleteDialogOpen(false);
      setContratoToDelete(null);
      setIsModalOpen(false);
      setSelectedContrato(null);
    } catch (err) {
      console.error('Erro ao excluir contrato:', err);
      showToast('Erro ao excluir contrato.', 'error');
    } finally {
      setIsDeleting(false);
    }
  };

  const handleCancelDelete = () => {
    setIsDeleteDialogOpen(false);
    setContratoToDelete(null);
  };

  const handleRemoveSignatureClick = (type: 'noiva' | 'noivo') => {
    setSignatureToRemove(type);
    setIsRemoveSignatureDialogOpen(true);
  };

  const handleConfirmRemoveSignature = async () => {
    if (!signatureToRemove || !selectedContrato || !supabase) return;

    setIsRemovingSignature(true);
    try {
      const updateData = signatureToRemove === 'noiva' 
        ? { assinatura_noiva: null }
        : { assinatura_noivo: null };

      const { error } = await (supabase as any)
        .from('contratos')
        .update(updateData)
        .eq('id', selectedContrato.id);

      if (error) throw error;

      // Atualizar estado local
      const updated = {
        ...selectedContrato,
        ...(signatureToRemove === 'noiva' 
          ? { assinaturaNoiva: undefined }
          : { assinaturaNoivo: undefined })
      };
      
      setSelectedContrato(updated);
      setContratos(prev => prev.map(c => c.id === selectedContrato.id ? updated : c));
      
      showToast(`Assinatura d${signatureToRemove === 'noiva' ? 'a noiva' : 'o noivo'} removida com sucesso!`, 'success');
      setIsRemoveSignatureDialogOpen(false);
      setSignatureToRemove(null);
    } catch (err) {
      console.error('Erro ao remover assinatura:', err);
      showToast('Erro ao remover assinatura.', 'error');
    } finally {
      setIsRemovingSignature(false);
    }
  };

  const handleCancelRemoveSignature = () => {
    setIsRemoveSignatureDialogOpen(false);
    setSignatureToRemove(null);
  };

  // Filtrar contratos com base na busca
  const filteredContratos = React.useMemo(() => {
    if (!searchQuery.trim()) return contratos;
    
    const query = searchQuery.toLowerCase();
    return contratos.filter(contrato => 
      contrato.clienteNome.toLowerCase().includes(query) ||
      contrato.valorTotal.toString().includes(query) ||
      (contrato.descricao?.toLowerCase().includes(query)) ||
      STATUS_LABELS[contrato.status].toLowerCase().includes(query)
    );
  }, [contratos, searchQuery]);

  return (
    <div className="w-full">
      {/* Header com título e botão */}
      <div className="mb-6">
        <div className="flex items-center justify-between mb-4">
          <h2 className="text-lg md:text-xl lg:text-2xl font-bold font-unbounded text-[#703535]">
            Contratos
          </h2>
          <button
            onClick={handleAddContrato}
            className="btn-primary-xs flex items-center gap-2"
          >
            <Plus className="size-4" />
            Novo Contrato
          </button>
        </div>
        {/* Barra de busca */}
        <div className="relative max-w-md">
          <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 size-4 text-gray-400" />
          <input
            type="text"
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            placeholder="Buscar contratos..."
            className="w-full pl-10 pr-4 py-2 border border-gray-300 rounded-lg text-sm bg-white"
          />
        </div>
      </div>

      {/* Tabela */}
      <div className="bg-white rounded-lg shadow-sm border border-gray-200 overflow-hidden">
        {isLoading ? (
          <div className="py-12 flex items-center justify-center">
            <Spinner size="md" />
          </div>
        ) : (
          <>
            <div className="overflow-x-auto">
              <table className="w-full">
                <thead className="bg-gray-50 border-b border-gray-200">
                  <tr>
                    <th className="px-4 py-3 text-left text-xs font-unbounded text-[#703535]">Noivos</th>
                    <th className="px-4 py-3 text-left text-xs font-unbounded text-[#703535]">Valor</th>
                    <th className="px-4 py-3 text-left text-xs font-unbounded text-[#703535]">Data da cerimônia</th>
                    <th className="px-4 py-3 text-left text-xs font-unbounded text-[#703535]">Status</th>
                    <th className="px-4 py-3 text-left text-xs font-unbounded text-[#703535]">Criado em</th>
                    <th className="px-4 py-3 text-center text-xs font-unbounded text-[#703535]"></th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-gray-200">
                  {filteredContratos.map((contrato) => (
                    <tr 
                      key={contrato.id} 
                      onClick={() => handleEditContrato(contrato)}
                      className="hover:bg-gray-50 transition-colors cursor-pointer"
                    >
                      <td className="px-4 py-3 text-sm text-gray-700">{contrato.clienteNome}</td>
                      <td className="px-4 py-3 text-sm text-gray-700">
                        R$ {contrato.valorTotal.toLocaleString('pt-BR', { minimumFractionDigits: 2 })}
                      </td>
                      <td className="px-4 py-3 text-sm text-gray-700">
                        {contrato.dataEvento ? format(new Date(`${contrato.dataEvento.split('T')[0]}T00:00:00`), "dd/MM/yyyy", { locale: ptBR }) : '-'}
                      </td>
                      <td className="px-4 py-3">
                        <Badge variant={STATUS_COLORS[contrato.status]} size="sm">
                          {STATUS_LABELS[contrato.status]}
                        </Badge>
                      </td>
                      <td className="px-4 py-3 text-sm text-gray-700">
                        {format(new Date(contrato.dataCriacao), "dd/MM/yyyy", { locale: ptBR })}
                      </td>
                      <td className="px-4 py-3">
                        <div className="flex items-center justify-center gap-2">
                          <a
                            href={`/contrato/${contrato.slug}`}
                            target="_blank"
                            rel="noopener noreferrer"
                            onClick={(e) => e.stopPropagation()}
                            className="p-1.5 hover:bg-gray-100 rounded transition-colors text-gray-600 hover:text-[#D65B58]"
                            title="Abrir contrato"
                          >
                            <ExternalLink className="size-4" />
                          </a>
                        </div>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>

            {filteredContratos.length === 0 && (
              <div className="py-12 text-center">
                <p className="text-gray-500 text-sm">
                  {searchQuery ? 'Nenhum contrato encontrado' : 'Nenhum contrato cadastrado'}
                </p>
              </div>
            )}
          </>
        )}
      </div>

      {/* Modal de Edição/Visualização */}
      <Dialog
        open={isModalOpen}
        onOpenChange={(open) => {
          if (open) setIsModalOpen(true);
          else handleCloseModal();
        }}
      >
        <DialogContent className="max-w-4xl max-h-[90vh] overflow-y-auto bg-[#F6EEE1]">
          {selectedContrato && (
            <>
              <DialogHeader>
                <DialogTitle className="text-2xl font-unbounded text-[#703535]">
                  {selectedContrato.clienteNome ? 'Editar Contrato' : 'Novo Contrato'}
                </DialogTitle>
              </DialogHeader>

              <div className="space-y-6 mt-4">
                <div className="p-6 space-y-4">
                  <div className="relative" ref={autocompleteRef}>
                    <label className="block text-sm font-medium text-gray-700 mb-1">
                      Nome dos Noivos *
                    </label>
                    {selectedContrato.id.startsWith('new-') && isEditing && propostas.length > 0 && (
                      <p className="text-xs text-gray-500 mb-2">
                        💡 Digite para buscar de uma proposta existente ou insira um novo nome
                      </p>
                    )}
                    <div className="relative">
                      <input
                        type="text"
                        value={selectedContrato.id.startsWith('new-') && isEditing ? autocompleteQuery : selectedContrato.clienteNome}
                        onChange={(e) => {
                          const value = e.target.value;
                          if (selectedContrato.id.startsWith('new-')) {
                            setAutocompleteQuery(value);
                            setShowAutocomplete(value.length > 0);
                            
                            // Gerar slug automaticamente apenas se não foi editado manualmente
                            if (!slugWasAutoGenerated) {
                              const autoSlug = createSlug(value);
                              setSelectedContrato({ ...selectedContrato, clienteNome: value, slug: autoSlug });
                            } else {
                              setSelectedContrato({ ...selectedContrato, clienteNome: value });
                            }
                          } else {
                            setSelectedContrato({ ...selectedContrato, clienteNome: value });
                          }
                        }}
                        onFocus={() => {
                          if (selectedContrato.id.startsWith('new-') && autocompleteQuery.length > 0) {
                            setShowAutocomplete(true);
                          }
                        }}
                        disabled={!isEditing}
                        className="w-full px-3 py-3 border border-gray-300 rounded-md text-sm bg-white"
                        placeholder="Digite o nome do casal ou busque de uma proposta"
                      />
                      {selectedContrato.id.startsWith('new-') && isEditing && propostas.length > 0 && (
                        <ChevronDown 
                          className="absolute right-3 top-1/2 -translate-y-1/2 size-4 text-gray-400 pointer-events-none" 
                        />
                      )}
                    </div>
                    {showAutocomplete && selectedContrato.id.startsWith('new-') && isEditing && (
                      <div className="absolute z-50 w-full mt-1 bg-white border border-gray-300 rounded-md shadow-lg max-h-60 overflow-auto">
                        {propostas
                          .filter(p => 
                            p.clienteNome.toLowerCase().includes(autocompleteQuery.toLowerCase())
                          )
                          .slice(0, 10)
                          .map(proposta => (
                            <button
                              key={proposta.id}
                              type="button"
                              onClick={() => handleSelectProposta(proposta)}
                              className="w-full px-4 py-3 text-left hover:bg-gray-50 border-b border-gray-100 last:border-b-0 transition-colors"
                            >
                              <div className="font-medium text-sm text-gray-900">
                                {proposta.clienteNome}
                              </div>
                              <div className="text-xs text-gray-500 mt-1 flex items-center gap-3">
                                {proposta.dataEvento && (
                                  <span>📅 {format(new Date(`${proposta.dataEvento.split('T')[0]}T00:00:00`), "dd/MM/yyyy", { locale: ptBR })}</span>
                                )}
                                {proposta.localFesta && (
                                  <span>📍 {proposta.localFesta}</span>
                                )}
                                <span>💰 R$ {proposta.valorTotal.toLocaleString('pt-BR', { minimumFractionDigits: 2 })}</span>
                              </div>
                            </button>
                          ))}
                        {propostas.filter(p => 
                          p.clienteNome.toLowerCase().includes(autocompleteQuery.toLowerCase())
                        ).length === 0 && (
                          <div className="px-4 py-3 text-sm text-gray-500 text-center">
                            Nenhuma proposta encontrada
                          </div>
                        )}
                      </div>
                    )}
                  </div>

                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div>
                      <label className="block text-sm font-medium text-gray-700 mb-1">
                        Nome da Noiva
                      </label>
                      <input
                        type="text"
                        value={selectedContrato.nomeNoiva || ''}
                        onChange={(e) => setSelectedContrato({ ...selectedContrato, nomeNoiva: e.target.value })}
                        disabled={!isEditing}
                        className="w-full px-3 py-3 border border-gray-300 rounded-md text-sm bg-white"
                        placeholder="Nome completo da noiva"
                      />
                    </div>

                    <div>
                      <label className="block text-sm font-medium text-gray-700 mb-1">
                        CPF da Noiva
                      </label>
                      <input
                        type="text"
                        value={selectedContrato.cpfNoiva || ''}
                        onChange={(e) => {
                          const value = e.target.value.replace(/\D/g, '');
                          const formatted = value
                            .replace(/(\d{3})(\d)/, '$1.$2')
                            .replace(/(\d{3})(\d)/, '$1.$2')
                            .replace(/(\d{3})(\d{1,2})$/, '$1-$2');
                          setSelectedContrato({ ...selectedContrato, cpfNoiva: formatted });
                        }}
                        disabled={!isEditing}
                        className="w-full px-3 py-3 border border-gray-300 rounded-md text-sm bg-white"
                        placeholder="000.000.000-00"
                        maxLength={14}
                      />
                    </div>
                  </div>

                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div>
                      <label className="block text-sm font-medium text-gray-700 mb-1">
                        Nome do Noivo
                      </label>
                      <input
                        type="text"
                        value={selectedContrato.nomeNoivo || ''}
                        onChange={(e) => setSelectedContrato({ ...selectedContrato, nomeNoivo: e.target.value })}
                        disabled={!isEditing}
                        className="w-full px-3 py-3 border border-gray-300 rounded-md text-sm bg-white"
                        placeholder="Nome completo do noivo"
                      />
                    </div>

                    <div>
                      <label className="block text-sm font-medium text-gray-700 mb-1">
                        CPF do Noivo
                      </label>
                      <input
                        type="text"
                        value={selectedContrato.cpfNoivo || ''}
                        onChange={(e) => {
                          const value = e.target.value.replace(/\D/g, '');
                          const formatted = value
                            .replace(/(\d{3})(\d)/, '$1.$2')
                            .replace(/(\d{3})(\d)/, '$1.$2')
                            .replace(/(\d{3})(\d{1,2})$/, '$1-$2');
                          setSelectedContrato({ ...selectedContrato, cpfNoivo: formatted });
                        }}
                        disabled={!isEditing}
                        className="w-full px-3 py-3 border border-gray-300 rounded-md text-sm bg-white"
                        placeholder="000.000.000-00"
                        maxLength={14}
                      />
                    </div>
                  </div>

                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1">
                      Endereço
                    </label>
                    <input
                      type="text"
                      value={selectedContrato.endereco || ''}
                      onChange={(e) => setSelectedContrato({ ...selectedContrato, endereco: e.target.value })}
                      disabled={!isEditing}
                      className="w-full px-3 py-3 border border-gray-300 rounded-md text-sm bg-white"
                      placeholder="Rua, número, bairro, cidade, estado"
                    />
                  </div>

                  {/* Assinaturas - Seção de Gerenciamento */}
                  {!selectedContrato.id.startsWith('new-') && (selectedContrato.assinaturaNoiva || selectedContrato.assinaturaNoivo) && (
                    <div className="border-t border-gray-300 pt-6">
                      <h3 className="text-sm font-medium text-gray-700 mb-4">Assinaturas Digitais</h3>
                      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                        {selectedContrato.assinaturaNoiva && selectedContrato.nomeNoiva && (
                          <div className="border border-gray-200 rounded-lg p-4 bg-gray-50">
                            <div className="flex items-start justify-between mb-2">
                              <div>
                                <p className="text-sm font-medium text-gray-900">Assinatura da Noiva</p>
                                <p className="text-xs text-gray-500">{selectedContrato.nomeNoiva}</p>
                              </div>
                              {isEditing && (
                                <button
                                  onClick={() => handleRemoveSignatureClick('noiva')}
                                  className="text-red-600 hover:text-red-700 p-1"
                                  title="Remover assinatura"
                                >
                                  <Trash2 className="w-4 h-4" />
                                </button>
                              )}
                            </div>
                            <div className="mt-2 border-t border-gray-300 pt-2">
                              <img 
                                src={selectedContrato.assinaturaNoiva} 
                                alt="Assinatura Noiva" 
                                className="h-16 w-auto object-contain"
                              />
                            </div>
                          </div>
                        )}

                        {selectedContrato.assinaturaNoivo && selectedContrato.nomeNoivo && (
                          <div className="border border-gray-200 rounded-lg p-4 bg-gray-50">
                            <div className="flex items-start justify-between mb-2">
                              <div>
                                <p className="text-sm font-medium text-gray-900">Assinatura do Noivo</p>
                                <p className="text-xs text-gray-500">{selectedContrato.nomeNoivo}</p>
                              </div>
                              {isEditing && (
                                <button
                                  onClick={() => handleRemoveSignatureClick('noivo')}
                                  className="text-red-600 hover:text-red-700 p-1"
                                  title="Remover assinatura"
                                >
                                  <Trash2 className="w-4 h-4" />
                                </button>
                              )}
                            </div>
                            <div className="mt-2 border-t border-gray-300 pt-2">
                              <img 
                                src={selectedContrato.assinaturaNoivo} 
                                alt="Assinatura Noivo" 
                                className="h-16 w-auto object-contain"
                              />
                            </div>
                          </div>
                        )}
                      </div>
                      <p className="text-xs text-gray-500 mt-3">
                        💡 Remova a assinatura se precisar que seja refeita. O(A) noivo(a) poderá assinar novamente acessando o link do contrato.
                      </p>
                    </div>
                  )}

                  <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                    <div className="md:col-span-1">
                      <label className="block text-sm font-medium text-gray-700 mb-1">
                        Data da Cerimônia *
                      </label>
                      <input
                        type="date"
                        value={selectedContrato.dataEvento ? selectedContrato.dataEvento.split('T')[0] : ''}
                        onChange={(e) => setSelectedContrato({ ...selectedContrato, dataEvento: e.target.value ? `${e.target.value}T00:00:00` : '' })}
                        disabled={!isEditing}
                        className="w-full px-3 py-3 border border-gray-300 rounded-md text-sm bg-white"
                      />
                    </div>

                    <div className="md:col-span-1">
                      <label className="block text-sm font-medium text-gray-700 mb-1">
                        Data do Contrato
                      </label>
                      <input
                        type="date"
                        value={selectedContrato.dataContrato ? selectedContrato.dataContrato.split('T')[0] : ''}
                        onChange={(e) => setSelectedContrato({ ...selectedContrato, dataContrato: e.target.value ? `${e.target.value}T00:00:00` : '' })}
                        disabled={!isEditing}
                        className="w-full px-3 py-3 border border-gray-300 rounded-md text-sm bg-white"
                      />
                    </div>

                    <div className="md:col-span-1">
                      <label className="block text-sm font-medium text-gray-700 mb-1">
                        Local da Festa
                      </label>
                      <input
                        type="text"
                        value={selectedContrato.localFesta || ''}
                        onChange={(e) => setSelectedContrato({ ...selectedContrato, localFesta: e.target.value })}
                        disabled={!isEditing}
                        className="w-full px-3 py-3 border border-gray-300 rounded-md text-sm bg-white"
                        placeholder="Local da festa"
                      />
                    </div>
                  </div>

                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div>
                      <label className="block text-sm font-medium text-gray-700 mb-1">
                        Número de Convidados
                      </label>
                      <input
                        type="number"
                        value={selectedContrato.numeroConvidados || ''}
                        onChange={(e) => setSelectedContrato({ ...selectedContrato, numeroConvidados: e.target.value ? parseInt(e.target.value) : undefined })}
                        disabled={!isEditing}
                        className="w-full px-3 py-3 border border-gray-300 rounded-md text-sm bg-white"
                        placeholder="Número de convidados"
                        min="0"
                      />
                    </div>

                    <div>
                      <label className="block text-sm font-medium text-gray-700 mb-1">
                        Status
                      </label>
                      <select
                        value={selectedContrato.status}
                        onChange={(e) => setSelectedContrato({ ...selectedContrato, status: e.target.value as Contrato['status'] })}
                        disabled={!isEditing}
                        className="w-full px-3 py-3 border border-gray-300 rounded-md text-sm bg-white"
                      >
                        <option value="rascunho">Rascunho</option>
                        <option value="ativo">Ativo</option>
                        <option value="concluido">Concluído</option>
                        <option value="cancelado">Cancelado</option>
                      </select>
                    </div>
                  </div>

                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1">
                      Valor Total *
                    </label>
                    <input
                      type="text"
                      value={selectedContrato.valorTotal.toLocaleString('pt-BR')}
                      onChange={(e) => {
                        const value = e.target.value.replace(/\./g, '').replace(',', '.');
                        setSelectedContrato({ ...selectedContrato, valorTotal: parseFloat(value) || 0 });
                      }}
                      disabled={!isEditing}
                      className="w-full px-3 py-3 border border-gray-300 rounded-md text-sm bg-white"
                      placeholder="0"
                    />
                  </div>

                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1">
                      Link do Contrato
                    </label>
                    <div className="flex gap-2">
                      <div className="flex-1 relative">
                        <span className="absolute left-3 top-1/2 -translate-y-1/2 text-sm text-gray-500">/contrato/</span>
                        <input
                          type="text"
                          value={selectedContrato.slug || ''}
                          onChange={(e) => {
                            const newSlug = e.target.value.toLowerCase().replace(/[^a-z0-9-]/g, '');
                            setSelectedContrato({ ...selectedContrato, slug: newSlug });
                            // Marcar que o slug foi editado manualmente
                            if (selectedContrato.id.startsWith('new-')) {
                              setSlugWasAutoGenerated(true);
                            }
                          }}
                          disabled={!isEditing}
                          className="w-full pl-24 pr-3 py-3 border border-gray-300 rounded-md text-sm bg-white"
                          placeholder="contrato-joao-maria"
                        />
                      </div>
                      {selectedContrato.slug && !selectedContrato.id.startsWith('new-') && (
                        <>
                          <button
                            type="button"
                            onClick={() => {
                              const url = `${window.location.origin}/contrato/${selectedContrato.slug}`;
                              navigator.clipboard.writeText(url);
                              showToast('Link copiado!', 'success');
                            }}
                            className="px-3 py-2 text-sm border border-gray-300 rounded-md hover:bg-gray-50 flex items-center gap-2"
                            title="Copiar link"
                          >
                            <Copy className="size-4" />
                          </button>
                          <a
                            href={`/contrato/${selectedContrato.slug}`}
                            target="_blank"
                            rel="noopener noreferrer"
                            className="px-3 py-2 text-sm border border-gray-300 rounded-md hover:bg-gray-50 flex items-center gap-2"
                            title="Abrir em nova aba"
                          >
                            <ExternalLink className="size-4" />
                          </a>
                        </>
                      )}
                    </div>
                  </div>

                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1">
                      Descrição
                    </label>
                    <textarea
                      value={selectedContrato.descricao || ''}
                      onChange={(e) => setSelectedContrato({ ...selectedContrato, descricao: e.target.value })}
                      disabled={!isEditing}
                      className="w-full px-3 py-3 border border-gray-300 rounded-md text-sm bg-white"
                      rows={5}
                      placeholder="Descrição do contrato"
                    />
                  </div>
                </div>

                {/* Botões de Ação */}
                {isEditing && (
                  <div className="flex items-center justify-end gap-3">
                    {!selectedContrato.id.startsWith('new-') && (
                      <button
                        onClick={() => handleDeleteClick(selectedContrato)}
                        className="btn-danger-xs-outline flex items-center gap-2"
                      >
                        <Trash2 className="w-4 h-4" />
                        Excluir Contrato
                      </button>
                    )}
                    <button
                      onClick={handleSaveContrato}
                      disabled={
                        isSaving || 
                        (!selectedContrato.id.startsWith('new-') && !hasChanges) ||
                        (selectedContrato.id.startsWith('new-') && (
                          !selectedContrato.clienteNome.trim() ||
                          !selectedContrato.dataEvento ||
                          selectedContrato.valorTotal <= 0
                        ))
                      }
                      className="btn-primary-xs flex items-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed"
                    >
                      <Check className="w-4 h-4" />
                      {isSaving ? 'Salvando...' : (selectedContrato.id.startsWith('new-') ? 'Criar Contrato' : 'Atualizar Contrato')}
                    </button>
                  </div>
                )}
              </div>
            </>
          )}
        </DialogContent>
      </Dialog>

      {/* Modal de Confirmação de Exclusão */}
      <Dialog open={isDeleteDialogOpen} onOpenChange={setIsDeleteDialogOpen}>
        <DialogContent className="max-w-md bg-[#F6EEE1]">
          <DialogHeader>
            <DialogTitle className="text-xl font-unbounded text-[#703535]">
              Confirmar Exclusão
            </DialogTitle>
          </DialogHeader>
          {contratoToDelete && (
            <div className="space-y-4">
              <p className="text-sm text-gray-700">
                Tem certeza que deseja excluir o contrato de <strong>{contratoToDelete.clienteNome}</strong>?
              </p>
              <p className="text-sm text-gray-600">
                Esta ação não pode ser desfeita.
              </p>
              <div className="flex items-center justify-end gap-3 mt-6">
                <button
                  onClick={handleCancelDelete}
                  disabled={isDeleting}
                  className="btn-secondary-xs-outline"
                >
                  Cancelar
                </button>
                <button
                  onClick={handleConfirmDelete}
                  disabled={isDeleting}
                  className="btn-danger-xs flex items-center gap-2"
                >
                  <Trash2 className="size-4" />
                  {isDeleting ? 'Excluindo...' : 'Excluir'}
                </button>
              </div>
            </div>
          )}
        </DialogContent>
      </Dialog>

      {/* Modal de Confirmação de Exclusão de Assinatura */}
      <Dialog open={isRemoveSignatureDialogOpen} onOpenChange={setIsRemoveSignatureDialogOpen}>
        <DialogContent className="max-w-md bg-[#F6EEE1]">
          <DialogHeader>
            <DialogTitle className="text-xl font-unbounded text-[#703535] flex items-center gap-2">
              <AlertCircle className="w-5 h-5 text-amber-600" />
              Remover Assinatura
            </DialogTitle>
          </DialogHeader>
          <div className="space-y-4">
            <p className="text-sm text-gray-700">
              Tem certeza que deseja remover a assinatura d{signatureToRemove === 'noiva' ? 'a noiva' : 'o noivo'}?
            </p>
            <div className="bg-amber-50 border border-amber-200 rounded-lg p-3">
              <p className="text-sm text-amber-800">
                <strong>Atenção:</strong> Esta ação permitirá que {signatureToRemove === 'noiva' ? 'a noiva' : 'o noivo'} assine novamente acessando o link do contrato.
              </p>
            </div>
            <div className="flex items-center justify-end gap-3 mt-6">
              <button
                onClick={handleCancelRemoveSignature}
                disabled={isRemovingSignature}
                className="btn-secondary-xs-outline"
              >
                Cancelar
              </button>
              <button
                onClick={handleConfirmRemoveSignature}
                disabled={isRemovingSignature}
                className="btn-danger-xs flex items-center gap-2"
              >
                <Trash2 className="size-4" />
                {isRemovingSignature ? 'Removendo...' : 'Remover Assinatura'}
              </button>
            </div>
          </div>
        </DialogContent>
      </Dialog>
    </div>
  );
}
