'use client';

import * as React from 'react';
import { Proposta } from '@/types/proposta';
import { mockPropostas } from '@/data/mock-propostas';
import { Badge } from '@/components/ui/badge-2';
import { format } from 'date-fns';
import { ptBR } from 'date-fns/locale';
import { DatePickerInput } from '@/components/ui/date-picker-input';
import { Plus, Edit, Search, Check, Trash2, X, ExternalLink, Copy, ChevronDown, ArrowUpDown, ArrowUp, ArrowDown } from 'lucide-react';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { Spinner } from '@/components/ui/spinner';
import { supabase, type PropostaUpdate, type PropostaInsert } from '@/lib/supabase';
import { useToast } from '@/components/ui/toast-1';
import { createSlug, isValidSlug } from '@/utils/slug';

const STATUS_LABELS: Record<Proposta['status'], string> = {
  rascunho: 'Rascunho',
  enviada: 'Enviada',
  aceita: 'Aceita',
  recusada: 'Recusada',
  expirada: 'Expirada',
};

const STATUS_STYLES: Record<Proposta['status'], string> = {
  rascunho: 'bg-[#ede8e3] text-[#8c7264]',
  enviada:  'bg-[#fdf0d8] text-[#9b6e20]',
  aceita:   'bg-[#e4f2e8] text-[#2e7042]',
  recusada: 'bg-[#ede8f5] text-[#6b4d8a]',
  expirada: 'bg-[#e8e8e8] text-[#737373]',
};

function StatusBadge({ status }: { status: Proposta['status'] }) {
  return (
    <span className={`inline-flex items-center px-3 py-0.5 rounded-full text-xs font-medium ${STATUS_STYLES[status]}`}>
      {STATUS_LABELS[status]}
    </span>
  );
}

type SortField = 'valorTotal' | 'dataEvento' | 'status' | 'dataCriacao';
type SortDir = 'asc' | 'desc' | 'original';

const STATUS_ORDER: Record<Proposta['status'], number> = {
  rascunho: 0,
  enviada: 1,
  aceita: 2,
  recusada: 3,
  expirada: 4,
};

type ColKey = 'noivos' | 'valor' | 'dataEvento' | 'status' | 'dataCriacao';
const DEFAULT_COL_ORDER: ColKey[] = ['noivos', 'valor', 'dataEvento', 'status', 'dataCriacao'];
const LS_COL_ORDER_KEY = 'propostas_col_order_v2';
const COL_LABELS: Record<ColKey, string> = {
  noivos: 'Noivos',
  valor: 'Valor',
  dataEvento: 'Data da cerimônia',
  status: 'Status',
  dataCriacao: 'Criada em',
};
const COL_SORT_FIELD: Partial<Record<ColKey, SortField>> = {
  valor: 'valorTotal',
  dataEvento: 'dataEvento',
  status: 'status',
  dataCriacao: 'dataCriacao',
};


const isUuid = (value: string) =>
  /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value);

interface LeadOption {
  id: string;
  nome_noivo: string | null;
  nome_noiva: string | null;
  data_casamento: string | null;
  local_evento: string | null;
  numero_convidados: number | null;
}

const dbStatusToUiStatus = (status: string | null | undefined): Proposta['status'] => {
  switch ((status || '').toLowerCase()) {
    case 'rascunho':
      return 'rascunho';
    case 'enviada':
      return 'enviada';
    case 'aceita':
      return 'aceita';
    case 'rejeitada':
    case 'recusada':
      return 'recusada';
    case 'expirada':
      return 'expirada';
    default:
      return 'enviada';
  }
};

const uiStatusToDbStatus = (status: Proposta['status']): string => {
  switch (status) {
    case 'recusada':
      return 'rejeitada';
    default:
      return status;
  }
};

export default function PropostasTable() {
  const { showToast } = useToast();
  const [propostas, setPropostas] = React.useState<Proposta[]>([]);
  const [isModalOpen, setIsModalOpen] = React.useState(false);
  const [isDeleteDialogOpen, setIsDeleteDialogOpen] = React.useState(false);
  const [propostaToDelete, setPropostaToDelete] = React.useState<Proposta | null>(null);
  const [selectedProposta, setSelectedProposta] = React.useState<Proposta | null>(null);
  const [isEditing, setIsEditing] = React.useState(false);
  const [searchQuery, setSearchQuery] = React.useState('');
  const [statusFilter, setStatusFilter] = React.useState<Proposta['status'] | 'todos'>('todos');
  const [sortField, setSortField] = React.useState<SortField | null>(null);
  const [sortDir, setSortDir] = React.useState<SortDir>('original');
  const [statusDropdownOpen, setStatusDropdownOpen] = React.useState(false);
  const statusDropdownRef = React.useRef<HTMLDivElement>(null);
  const [colOrder, setColOrder] = React.useState<ColKey[]>(DEFAULT_COL_ORDER);
  const dragColRef = React.useRef<number | null>(null);
  const [dragOverCol, setDragOverCol] = React.useState<number | null>(null);
  const [isLoading, setIsLoading] = React.useState(true);
  const [isSaving, setIsSaving] = React.useState(false);
  const [isDeleting, setIsDeleting] = React.useState(false);
  const [activeTab, setActiveTab] = React.useState<'cliente' | 'proposta' | 'pagamento'>('cliente');
  const [hasChanges, setHasChanges] = React.useState(false);
  const [originalProposta, setOriginalProposta] = React.useState<Proposta | null>(null);
  const [slugWasAutoGenerated, setSlugWasAutoGenerated] = React.useState(false);

  // Lead search
  const [leads, setLeads] = React.useState<LeadOption[]>([]);
  const [selectedLeadId, setSelectedLeadId] = React.useState<string | null>(null);
  const [leadSearch, setLeadSearch] = React.useState('');
  const [showLeadDropdown, setShowLeadDropdown] = React.useState(false);
  const leadDropdownRef = React.useRef<HTMLDivElement>(null);

  // Carregar propostas do Supabase (fallback para mock se Supabase não estiver configurado)
  React.useEffect(() => {
    let cancelled = false;

    const load = async () => {
      try {
        if (!supabase) {
          if (!cancelled) {
            setPropostas(mockPropostas);
            setIsLoading(false);
          }
          return;
        }

        const { data, error } = await (supabase as any)
          .from('propostas')
          .select('id, lead_id, titulo, descricao, valor_total, status, data_proposta, validade_ate, created_at, itens, slug, local_festa, numero_convidados, link_pagamento_7_dias, link_pagamento_21_dias')
          .order('created_at', { ascending: false });

        if (error) throw error;

        const mapped: Proposta[] = (data || []).map((row: any) => ({
          id: String(row.id),
          clienteNome: String(row.titulo ?? ''),
          valorTotal: Number(row.valor_total ?? 0),
          status: dbStatusToUiStatus(row.status),
          dataCriacao: row.data_proposta ? `${row.data_proposta}T00:00:00` : String(row.created_at ?? new Date().toISOString()),
          dataEvento: row.validade_ate ? `${row.validade_ate}T00:00:00` : '',
          descricao: row.descricao ?? undefined,
          slug: row.slug ?? undefined,
          localFesta: row.local_festa ?? undefined,
          numeroConvidados: row.numero_convidados ?? undefined,
          linkPagamento7Dias: row.link_pagamento_7_dias ?? undefined,
          linkPagamento21Dias: row.link_pagamento_21_dias ?? undefined,
          itens: (Array.isArray(row.itens) ? row.itens : []) as any,
        }));

        if (!cancelled) {
          setPropostas(mapped);
          setIsLoading(false);
        }
      } catch (err) {
        console.error('Erro ao carregar propostas:', err);
        if (!cancelled) {
          setPropostas(mockPropostas);
          setIsLoading(false);
          showToast('Não foi possível carregar do Supabase (usando dados locais).', 'warning');
        }
      }
    };

    load();
    return () => {
      cancelled = true;
    };
  }, [showToast]);

  // Carregar leads para o combobox de busca
  React.useEffect(() => {
    if (!supabase) return;
    (supabase as any)
      .from('leads')
      .select('id, nome_noivo, nome_noiva, data_casamento, local_evento, numero_convidados')
      .order('created_at', { ascending: false })
      .then(({ data }: { data: LeadOption[] | null }) => {
        setLeads(data || []);
      });
  }, []);

  // Fechar dropdown ao clicar fora
  React.useEffect(() => {
    const handleClickOutside = (e: MouseEvent) => {
      if (leadDropdownRef.current && !leadDropdownRef.current.contains(e.target as Node)) {
        setShowLeadDropdown(false);
      }
    };
    document.addEventListener('mousedown', handleClickOutside);
    return () => document.removeEventListener('mousedown', handleClickOutside);
  }, []);

  // Detectar mudanças comparando proposta atual com original
  React.useEffect(() => {
    if (!selectedProposta || !originalProposta) {
      setHasChanges(false);
      return;
    }

    const changed = JSON.stringify(selectedProposta) !== JSON.stringify(originalProposta);
    setHasChanges(changed);
  }, [selectedProposta, originalProposta]);

  const handleAddProposta = () => {
    const newProposta: Proposta = {
      id: `new-${Date.now()}`,
      clienteNome: '',
      valorTotal: 0,
      status: 'rascunho',
      dataCriacao: new Date().toISOString(),
      dataEvento: '',
      descricao: '',
      slug: '',
      itens: [],
    };
    setSelectedProposta(newProposta);
    setOriginalProposta(null);
    setHasChanges(false);
    setIsEditing(true);
    setActiveTab('cliente');
    setSlugWasAutoGenerated(false);
    setSelectedLeadId(null);
    setLeadSearch('');
    setShowLeadDropdown(false);
    setIsModalOpen(true);
  };

  const handleEditProposta = (proposta: Proposta) => {
    setSelectedProposta(proposta);
    setOriginalProposta(JSON.parse(JSON.stringify(proposta)));
    setHasChanges(false);
    setIsEditing(true);
    setActiveTab('cliente');
    setSlugWasAutoGenerated(false);
    setSelectedLeadId(null);
    setLeadSearch(proposta.clienteNome);
    setShowLeadDropdown(false);
    setIsModalOpen(true);
  };

  const handleSaveProposta = async () => {
    if (!selectedProposta) return;

    if (!selectedProposta.clienteNome.trim()) {
      showToast('Informe o nome do cliente.', 'warning');
      return;
    }

    // Validar slug se fornecido
    if (selectedProposta.slug && !isValidSlug(selectedProposta.slug)) {
      showToast('URL inválida. Use apenas letras minúsculas, números e hífens.', 'warning');
      return;
    }

    const isNewProposta = selectedProposta.id.startsWith('new-');

    // Gerar slug automaticamente se não fornecido
    let slug = selectedProposta.slug?.trim() || createSlug(selectedProposta.clienteNome);

    // Fallback: sem Supabase configurado, mantém comportamento local
    if (!supabase) {
      if (isNewProposta) {
        const newId = `local-${Date.now()}`;
        const newProposta = { ...selectedProposta, id: newId, slug };
        setPropostas([...propostas, newProposta]);
      } else {
        setPropostas(propostas.map((p) => (p.id === selectedProposta.id ? { ...selectedProposta, slug } : p)));
      }
      setIsModalOpen(false);
      setSelectedProposta(null);
      showToast('Proposta salva localmente (Supabase não configurado).', 'warning');
      return;
    }

    setIsSaving(true);
    try {
      if (isNewProposta) {
        // Criar nova proposta - lead_id opcional (vem do combobox de busca)
        const payload: PropostaInsert = {
          lead_id: selectedLeadId || null,
          titulo: selectedProposta.clienteNome.trim(),
          descricao: selectedProposta.descricao?.trim() || null,
          slug: slug || null,
          valor_total: selectedProposta.valorTotal,
          status: uiStatusToDbStatus(selectedProposta.status),
          data_proposta: selectedProposta.dataCriacao 
            ? (selectedProposta.dataCriacao.includes('T') ? selectedProposta.dataCriacao.split('T')[0] : selectedProposta.dataCriacao)
            : null,
          validade_ate: selectedProposta.dataEvento 
            ? (selectedProposta.dataEvento.includes('T') ? selectedProposta.dataEvento.split('T')[0] : selectedProposta.dataEvento)
            : null,
          local_festa: selectedProposta.localFesta?.trim() || null,
          numero_convidados: selectedProposta.numeroConvidados ?? null,
          link_pagamento_7_dias: selectedProposta.linkPagamento7Dias?.trim() || null,
          link_pagamento_21_dias: selectedProposta.linkPagamento21Dias?.trim() || null,
          itens: (selectedProposta.itens as any) ?? [],
        };

        const { data, error } = await (supabase as any)
          .from('propostas')
          .insert(payload)
          .select('id, titulo, descricao, valor_total, status, data_proposta, validade_ate, created_at, itens, slug, local_festa, numero_convidados, link_pagamento_7_dias, link_pagamento_21_dias')
          .single();

        if (error) throw error;

        const newProposta: Proposta = {
          id: String(data.id),
          clienteNome: String(data.titulo ?? ''),
          valorTotal: Number(data.valor_total ?? 0),
          status: dbStatusToUiStatus(data.status),
          dataCriacao: data.data_proposta ? `${data.data_proposta}T00:00:00` : String(data.created_at ?? new Date().toISOString()),
          dataEvento: data.validade_ate ? `${data.validade_ate}T00:00:00` : '',
          descricao: data.descricao ?? undefined,
          slug: data.slug ?? undefined,
          localFesta: data.local_festa ?? undefined,
          numeroConvidados: data.numero_convidados ?? undefined,
          linkPagamento7Dias: data.link_pagamento_7_dias ?? undefined,
          linkPagamento21Dias: data.link_pagamento_21_dias ?? undefined,
          itens: (Array.isArray(data.itens) ? data.itens : []) as any,
        };

        setPropostas((prev) => [newProposta, ...prev]);
        setIsModalOpen(false);
        setSelectedProposta(null);
        setHasChanges(false);
        setOriginalProposta(null);
        showToast('Proposta criada com sucesso!', 'success');
      } else {
        // Atualizar proposta existente
        if (!isUuid(selectedProposta.id)) {
          showToast('ID inválido para atualização.', 'warning');
          setIsSaving(false);
          return;
        }

        const payload: PropostaUpdate = {
          titulo: selectedProposta.clienteNome.trim(),
          descricao: selectedProposta.descricao?.trim() ? selectedProposta.descricao.trim() : null,
          slug: slug || null,
          valor_total: selectedProposta.valorTotal,
          status: uiStatusToDbStatus(selectedProposta.status),
          data_proposta: selectedProposta.dataCriacao 
            ? (selectedProposta.dataCriacao.includes('T') ? selectedProposta.dataCriacao.split('T')[0] : selectedProposta.dataCriacao)
            : null,
          validade_ate: selectedProposta.dataEvento 
            ? (selectedProposta.dataEvento.includes('T') ? selectedProposta.dataEvento.split('T')[0] : selectedProposta.dataEvento)
            : null,
          local_festa: selectedProposta.localFesta?.trim() || null,
          numero_convidados: selectedProposta.numeroConvidados ?? null,
          link_pagamento_7_dias: selectedProposta.linkPagamento7Dias?.trim() || null,
          link_pagamento_21_dias: selectedProposta.linkPagamento21Dias?.trim() || null,
          itens: (selectedProposta.itens as any) ?? [],
        };

        const { data, error } = await (supabase as any)
          .from('propostas')
          .update(payload)
          .eq('id', selectedProposta.id)
          .select('id, titulo, descricao, valor_total, status, data_proposta, validade_ate, created_at, itens, slug, local_festa, numero_convidados, link_pagamento_7_dias, link_pagamento_21_dias')
          .single();

        if (error) throw error;

        const updated: Proposta = {
          id: String(data.id),
          clienteNome: String(data.titulo ?? ''),
          valorTotal: Number(data.valor_total ?? 0),
          status: dbStatusToUiStatus(data.status),
          dataCriacao: data.data_proposta ? `${data.data_proposta}T00:00:00` : String(data.created_at ?? selectedProposta.dataCriacao),
          dataEvento: data.validade_ate ? `${data.validade_ate}T00:00:00` : '',
          descricao: data.descricao ?? undefined,
          slug: data.slug ?? undefined,
          localFesta: data.local_festa ?? undefined,
          numeroConvidados: data.numero_convidados ?? undefined,
          linkPagamento7Dias: data.link_pagamento_7_dias ?? undefined,
          linkPagamento21Dias: data.link_pagamento_21_dias ?? undefined,
          itens: (Array.isArray(data.itens) ? data.itens : []) as any,
        };

        setPropostas((prev) => prev.map((p) => (p.id === updated.id ? updated : p)));
        setIsModalOpen(false);
        setSelectedProposta(null);
        setHasChanges(false);
        setOriginalProposta(null);
        showToast('Proposta atualizada com sucesso!', 'success');
      }
    } catch (err) {
      console.error('Erro ao salvar proposta:', err);
      showToast('Erro ao salvar no Supabase.', 'error');
    } finally {
      setIsSaving(false);
    }
  };

  const handleCloseModal = () => {
    setIsModalOpen(false);
    setTimeout(() => {
      setSelectedProposta(null);
      setIsEditing(false);
      setHasChanges(false);
      setOriginalProposta(null);
    }, 200);
  };

  const handleDeleteClick = (proposta: Proposta) => {
    setPropostaToDelete(proposta);
    setIsDeleteDialogOpen(true);
  };

  const handleConfirmDelete = async () => {
    if (!propostaToDelete) return;

    // Fallback: sem Supabase configurado, mantém comportamento local
    if (!supabase) {
      setPropostas(propostas.filter((p) => p.id !== propostaToDelete.id));
      setIsDeleteDialogOpen(false);
      setPropostaToDelete(null);
      setIsModalOpen(false);
      setSelectedProposta(null);
      showToast('Proposta excluída localmente (Supabase não configurado).', 'warning');
      return;
    }

    if (!isUuid(propostaToDelete.id)) {
      showToast('Não é possível excluir proposta local do Supabase.', 'warning');
      return;
    }

    setIsDeleting(true);
    try {
      const { error } = await (supabase as any)
        .from('propostas')
        .delete()
        .eq('id', propostaToDelete.id);

      if (error) throw error;

      setPropostas((prev) => prev.filter((p) => p.id !== propostaToDelete.id));
      showToast('Proposta excluída com sucesso!', 'success');
      setIsDeleteDialogOpen(false);
      setPropostaToDelete(null);
      setIsModalOpen(false);
      setSelectedProposta(null);
    } catch (err) {
      console.error('Erro ao excluir proposta:', err);
      showToast('Erro ao excluir proposta.', 'error');
    } finally {
      setIsDeleting(false);
    }
  };

  const handleCancelDelete = () => {
    setIsDeleteDialogOpen(false);
    setPropostaToDelete(null);
  };

  // Fechar status dropdown ao clicar fora
  React.useEffect(() => {
    const handleClickOutside = (e: MouseEvent) => {
      if (statusDropdownRef.current && !statusDropdownRef.current.contains(e.target as Node)) {
        setStatusDropdownOpen(false);
      }
    };
    document.addEventListener('mousedown', handleClickOutside);
    return () => document.removeEventListener('mousedown', handleClickOutside);
  }, []);

  // Carregar ordem das colunas do localStorage
  React.useEffect(() => {
    try {
      const saved = localStorage.getItem(LS_COL_ORDER_KEY);
      if (saved) {
        const parsed = JSON.parse(saved) as ColKey[];
        if (
          Array.isArray(parsed) &&
          parsed.length === DEFAULT_COL_ORDER.length &&
          parsed.every(k => k in COL_LABELS)
        ) {
          setColOrder(parsed);
        }
      }
    } catch {}
  }, []);

  const handleSort = (field: SortField) => {
    if (sortField !== field) {
      setSortField(field);
      setSortDir('asc');
    } else {
      const nextDir: SortDir = sortDir === 'asc' ? 'desc' : sortDir === 'desc' ? 'original' : 'asc';
      setSortDir(nextDir);
      if (nextDir === 'original') setSortField(null);
    }
  };

  function SortIcon({ field }: { field: SortField }) {
    if (sortField !== field || sortDir === 'original') return <ArrowUpDown className="size-3 ml-1 opacity-40" />;
    if (sortDir === 'asc') return <ArrowUp className="size-3 ml-1 text-[#D65B58]" />;
    return <ArrowDown className="size-3 ml-1 text-[#D65B58]" />;
  }


  const filteredPropostas = React.useMemo(() => {
    let result = [...propostas];

    if (searchQuery.trim()) {
      const query = searchQuery.toLowerCase();
      result = result.filter(p =>
        p.clienteNome.toLowerCase().includes(query) ||
        p.valorTotal.toString().includes(query) ||
        (p.descricao?.toLowerCase().includes(query)) ||
        STATUS_LABELS[p.status].toLowerCase().includes(query)
      );
    }

    if (statusFilter !== 'todos') {
      result = result.filter(p => p.status === statusFilter);
    }

    if (sortField && sortDir !== 'original') {
      result.sort((a, b) => {
        let cmp = 0;
        if (sortField === 'valorTotal') {
          cmp = a.valorTotal - b.valorTotal;
        } else if (sortField === 'dataEvento') {
          const da = a.dataEvento ? new Date(a.dataEvento).getTime() : 0;
          const db = b.dataEvento ? new Date(b.dataEvento).getTime() : 0;
          cmp = da - db;
        } else if (sortField === 'status') {
          cmp = STATUS_ORDER[a.status] - STATUS_ORDER[b.status];
        } else if (sortField === 'dataCriacao') {
          cmp = new Date(a.dataCriacao).getTime() - new Date(b.dataCriacao).getTime();
        }
        return sortDir === 'asc' ? cmp : -cmp;
      });
    }

    return result;
  }, [propostas, searchQuery, statusFilter, sortField, sortDir]);

  return (
    <div className="w-full">
      {/* Header com título e botão */}
      <div className="mb-6">
        <div className="flex items-center justify-between mb-4">
          <h2 className="text-lg md:text-xl lg:text-2xl font-bold font-unbounded text-[#703535]">
            Propostas
          </h2>
          <button
            onClick={handleAddProposta}
            className="btn-primary-xs flex items-center gap-2"
          >
            <Plus className="size-4" />
            Nova Proposta
          </button>
        </div>
        {/* Barra de busca + filtro de status */}
        <div className="flex items-center gap-3 flex-wrap">
          <div className="relative max-w-md flex-1">
            <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 size-4 text-gray-400" />
            <input
              type="text"
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              placeholder="Buscar propostas..."
              className="w-full pl-10 pr-4 py-2 border border-gray-300 rounded-lg text-sm bg-white"
            />
          </div>
          {/* Dropdown filtro de status */}
          <div className="relative" ref={statusDropdownRef}>
            <button
              onClick={() => setStatusDropdownOpen(o => !o)}
              className="flex items-center gap-2 px-3 py-2 border border-gray-300 rounded-lg text-sm bg-white hover:border-[#D65B58] transition-colors min-w-[140px] justify-between cursor-pointer h-[38px]"
            >
              <span className={`font-unbounded font-medium text-xs ${statusFilter === 'todos' ? 'text-gray-400' : 'text-gray-700'}`}>
                {statusFilter === 'todos' ? 'Todos os status' : STATUS_LABELS[statusFilter]}
              </span>
              <ChevronDown className="size-4 text-gray-400 shrink-0" />
            </button>
            {statusDropdownOpen && (
              <div className="absolute left-0 top-full mt-1 z-20 bg-white border border-gray-200 rounded-lg shadow-md py-1 min-w-[160px]">
                <button
                  onClick={() => { setStatusFilter('todos'); setStatusDropdownOpen(false); }}
                  className={`w-full text-left px-4 py-2 text-xs font-unbounded font-medium hover:bg-gray-50 cursor-pointer ${statusFilter === 'todos' ? 'text-[#D65B58]' : 'text-gray-700'}`}
                >
                  Todos
                </button>
                {(Object.keys(STATUS_LABELS) as Proposta['status'][]).map(s => (
                  <button
                    key={s}
                    onClick={() => { setStatusFilter(s); setStatusDropdownOpen(false); }}
                    className={`w-full text-left px-4 py-2 text-sm hover:bg-gray-50 flex items-center gap-2 cursor-pointer ${statusFilter === s ? 'text-[#D65B58] font-medium' : 'text-gray-700'}`}
                  >
                    <span className={`inline-flex px-2 py-0.5 rounded-full text-xs font-medium ${STATUS_STYLES[s]}`}>{STATUS_LABELS[s]}</span>
                  </button>
                ))}
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Tabela */}
      <div className="bg-white rounded-lg shadow-sm border border-gray-200 overflow-hidden">
        {isLoading ? (
          <div className="py-12 flex items-center justify-center">
            <Spinner size="md" />
          </div>
        ) : (
          <>
            <div className="overflow-x-auto">
              <table className="w-full">
                <thead className="bg-gray-50 border-b border-gray-200">
                  <tr>
                    {colOrder.map((col, index) => {
                      const sortField = COL_SORT_FIELD[col];
                      return (
                        <th
                          key={col}
                          draggable
                          onDragStart={() => { dragColRef.current = index; }}
                          onDragOver={(e) => { e.preventDefault(); setDragOverCol(index); }}
                          onDrop={() => {
                            if (dragColRef.current === null || dragColRef.current === index) {
                              setDragOverCol(null);
                              return;
                            }
                            const newOrder = [...colOrder];
                            const [moved] = newOrder.splice(dragColRef.current, 1);
                            newOrder.splice(index, 0, moved);
                            setColOrder(newOrder);
                            localStorage.setItem(LS_COL_ORDER_KEY, JSON.stringify(newOrder));
                            dragColRef.current = null;
                            setDragOverCol(null);
                          }}
                          onDragEnd={() => { dragColRef.current = null; setDragOverCol(null); }}
                          onClick={() => { if (sortField) handleSort(sortField); }}
                          style={dragOverCol === index ? { borderLeft: '2px solid #D65B58' } : undefined}
                          className={`px-4 py-3 text-left text-xs font-unbounded text-[#703535] select-none cursor-grab active:cursor-grabbing${sortField ? ' hover:text-[#D65B58]' : ''}`}
                        >
                          <span className="flex items-center">
                            {COL_LABELS[col]}
                            {sortField && <SortIcon field={sortField} />}
                          </span>
                        </th>
                      );
                    })}
                    <th className="px-4 py-3 text-center text-xs font-unbounded text-[#703535]"></th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-gray-200">
                  {filteredPropostas.map((proposta) => (
                    <tr 
                      key={proposta.id} 
                      onClick={() => handleEditProposta(proposta)}
                      className="hover:bg-gray-50 transition-[background-color] cursor-pointer"
                    >
                      {colOrder.map((col) => {
                        switch (col) {
                          case 'noivos':
                            return <td key={col} className="px-4 py-3 text-sm text-gray-700">{proposta.clienteNome}</td>;
                          case 'valor':
                            return <td key={col} className="px-4 py-3 text-sm text-gray-700">R$ {proposta.valorTotal.toLocaleString('pt-BR', { minimumFractionDigits: proposta.valorTotal % 1 === 0 ? 0 : 2, maximumFractionDigits: 2 })}</td>;
                          case 'dataEvento':
                            return <td key={col} className="px-4 py-3 text-sm text-gray-700">{proposta.dataEvento ? format(new Date(`${proposta.dataEvento.split('T')[0]}T00:00:00`), 'dd/MM/yyyy', { locale: ptBR }) : '-'}</td>;
                          case 'status':
                            return <td key={col} className="px-4 py-3"><StatusBadge status={proposta.status} /></td>;
                          case 'dataCriacao':
                            return <td key={col} className="px-4 py-3 text-sm text-gray-700">{format(new Date(proposta.dataCriacao), 'dd/MM/yyyy', { locale: ptBR })}</td>;
                          default:
                            return null;
                        }
                      })}
                      <td className="px-4 py-3">
                        <div className="flex items-center justify-center gap-2">
                          <a
                            href={`/proposta/${proposta.slug}`}
                            target="_blank"
                            rel="noopener noreferrer"
                            onClick={(e) => e.stopPropagation()}
                            className="p-1.5 hover:bg-gray-100 rounded transition-colors text-gray-600 hover:text-[#D65B58]"
                            title="Abrir proposta"
                          >
                            <ExternalLink className="size-4" />
                          </a>
                        </div>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>

            {filteredPropostas.length === 0 && (
              <div className="py-12 text-center">
                <p className="text-gray-500 text-sm">
                  {searchQuery || statusFilter !== 'todos' ? 'Nenhuma proposta encontrada' : 'Nenhuma proposta cadastrada'}
                </p>
              </div>
            )}
          </>
        )}
      </div>

      {/* Modal de Edição/Visualização */}
      <Dialog
        open={isModalOpen}
        onOpenChange={(open) => {
          if (open) setIsModalOpen(true);
          else handleCloseModal();
        }}
      >
        <DialogContent className="max-w-4xl max-h-[90vh] overflow-y-auto bg-[#F6EEE1]">
          {selectedProposta && (
            <>
              <DialogHeader>
                <DialogTitle className="text-2xl font-unbounded text-[#703535] text-left">
                  {selectedProposta.clienteNome ? 'Editar Proposta' : 'Nova Proposta'}
                </DialogTitle>
              </DialogHeader>

              {/* Tabs Navigation */}
              <div className="flex border-b border-gray-300 mt-4">
                <button
                  onClick={() => setActiveTab('cliente')}
                  className={`px-6 py-3 font-unbounded font-medium text-sm transition-colors cursor-pointer ${
                    activeTab === 'cliente'
                      ? 'text-[#D65B58] border-b-2 border-[#D65B58]'
                      : 'text-[#703535] hover:text-[#D65B58] border-b-2 border-transparent'
                  }`}
                >
                  Cliente
                </button>
                <button
                  onClick={() => setActiveTab('proposta')}
                  className={`px-6 py-3 font-unbounded font-medium text-sm transition-colors cursor-pointer ${
                    activeTab === 'proposta'
                      ? 'text-[#D65B58] border-b-2 border-[#D65B58]'
                      : 'text-[#703535] hover:text-[#D65B58] border-b-2 border-transparent'
                  }`}
                >
                  Proposta
                </button>
                <button
                  onClick={() => setActiveTab('pagamento')}
                  className={`px-6 py-3 font-unbounded font-medium text-sm transition-colors cursor-pointer ${
                    activeTab === 'pagamento'
                      ? 'text-[#D65B58] border-b-2 border-[#D65B58]'
                      : 'text-[#703535] hover:text-[#D65B58] border-b-2 border-transparent'
                  }`}
                >
                  Pagamento
                </button>
              </div>

              <div className="space-y-6 mt-4">
                {/* Tab: Cliente */}
                {activeTab === 'cliente' && (
                  <div className="p-6 space-y-4">
                    {/* Lead search combobox */}
                    <div ref={leadDropdownRef} className="relative">
                      <label className="block text-sm font-medium text-gray-700 mb-1">
                        Nome dos Noivos *
                      </label>
                      <div className="relative">
                        <input
                          type="text"
                          value={leadSearch}
                          onChange={(e) => {
                            const val = e.target.value;
                            setLeadSearch(val);
                            setSelectedLeadId(null);
                            setShowLeadDropdown(val.length > 0);
                            // Sync nome no form
                            const newClienteNome = val;
                            if (selectedProposta!.id.startsWith('new-') && !slugWasAutoGenerated) {
                              setSelectedProposta({ ...selectedProposta!, clienteNome: newClienteNome, slug: createSlug(newClienteNome) });
                            } else {
                              setSelectedProposta({ ...selectedProposta!, clienteNome: newClienteNome });
                            }
                          }}
                          onFocus={() => {
                            if (leadSearch.length > 0) setShowLeadDropdown(true);
                          }}
                          disabled={!isEditing}
                          className="w-full px-3 py-3 border border-gray-300 rounded-md text-sm bg-white pr-10"
                          placeholder="Digite ou busque pelo nome do casal"
                        />
                        <ChevronDown className="pointer-events-none absolute right-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400" />
                      </div>
                      {showLeadDropdown && isEditing && (() => {
                        const q = leadSearch.toLowerCase();
                        const filtered = leads.filter(l =>
                          (l.nome_noivo || '').toLowerCase().includes(q) ||
                          (l.nome_noiva || '').toLowerCase().includes(q)
                        );
                        return filtered.length > 0 ? (
                          <ul className="absolute z-50 mt-1 w-full bg-white border border-gray-200 rounded-md shadow-lg max-h-56 overflow-y-auto">
                            {filtered.map((lead) => {
                              const nome = [lead.nome_noivo, lead.nome_noiva].filter(Boolean).join(' e ');
                              return (
                                <li
                                  key={lead.id}
                                  onMouseDown={(e) => {
                                    e.preventDefault();
                                    setSelectedLeadId(lead.id);
                                    setLeadSearch(nome);
                                    setShowLeadDropdown(false);
                                    const autoSlug = selectedProposta!.id.startsWith('new-') && !slugWasAutoGenerated
                                      ? createSlug(nome)
                                      : selectedProposta!.slug;
                                    setSelectedProposta({
                                      ...selectedProposta!,
                                      clienteNome: nome,
                                      slug: autoSlug,
                                      dataEvento: lead.data_casamento
                                        ? `${lead.data_casamento}T00:00:00`
                                        : selectedProposta!.dataEvento,
                                      localFesta: lead.local_evento || selectedProposta!.localFesta,
                                      numeroConvidados: lead.numero_convidados ?? selectedProposta!.numeroConvidados,
                                    });
                                  }}
                                  className="flex items-center justify-between px-3 py-2 text-sm hover:bg-[#F3ECE9] cursor-pointer"
                                >
                                  <span className="font-medium text-gray-800">{nome}</span>
                                  {lead.data_casamento && (
                                    <span className="text-xs text-gray-400 ml-2 shrink-0">
                                      {new Date(lead.data_casamento + 'T12:00:00').toLocaleDateString('pt-BR')}
                                    </span>
                                  )}
                                </li>
                              );
                            })}
                          </ul>
                        ) : null;
                      })()}
                      {selectedLeadId && (
                        <p className="mt-1 text-xs text-[#703535]">Lead vinculado ✓</p>
                      )}
                    </div>

                    <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                      <DatePickerInput
                        value={selectedProposta.dataEvento ? selectedProposta.dataEvento.split('T')[0] : ''}
                        onChange={(value) => setSelectedProposta({ ...selectedProposta, dataEvento: value ? `${value}T00:00:00` : '' })}
                        label="Data da Cerimônia *"
                        placeholder="Selecione a data"
                        disabled={!isEditing}
                        className="md:col-span-1"
                      />

                      <div className="md:col-span-2">
                        <label className="block text-sm font-medium text-gray-700 mb-1">
                          Local da Festa *
                        </label>
                        <input
                          type="text"
                          value={selectedProposta.localFesta || ''}
                          onChange={(e) => setSelectedProposta({ ...selectedProposta, localFesta: e.target.value })}
                          disabled={!isEditing}
                          className="w-full px-3 py-3 border border-gray-300 rounded-md text-sm bg-white"
                          placeholder="Local da festa"
                        />
                      </div>
                    </div>

                    <div>
                      <label className="block text-sm font-medium text-gray-700 mb-1">
                        Número de Convidados
                      </label>
                      <input
                        type="number"
                        value={selectedProposta.numeroConvidados || ''}
                        onChange={(e) => setSelectedProposta({ ...selectedProposta, numeroConvidados: e.target.value ? parseInt(e.target.value) : undefined })}
                        disabled={!isEditing}
                        className="w-full px-3 py-3 border border-gray-300 rounded-md text-sm bg-white"
                        placeholder="Número de convidados"
                        min="0"
                      />
                    </div>
                  </div>
                )}

                {/* Tab: Proposta */}
                {activeTab === 'proposta' && (
                  <div className="p-6 space-y-4">
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                      <DatePickerInput
                        value={selectedProposta.dataCriacao ? selectedProposta.dataCriacao.split('T')[0] : ''}
                        onChange={(value) => setSelectedProposta({ ...selectedProposta, dataCriacao: value ? `${value}T00:00:00` : new Date().toISOString() })}
                        label="Data da Proposta"
                        placeholder="Selecione a data"
                        disabled={!isEditing}
                      />

                      <div>
                        <label className="block text-sm font-medium text-gray-700 mb-1">
                          Status
                        </label>
                        <select
                          value={selectedProposta.status}
                          onChange={(e) => setSelectedProposta({ ...selectedProposta, status: e.target.value as Proposta['status'] })}
                          disabled={!isEditing}
                          className="w-full px-3 py-3 border border-gray-300 rounded-md text-sm bg-white"
                        >
                          <option value="rascunho">Rascunho</option>
                          <option value="enviada">Enviada</option>
                          <option value="aceita">Aceita</option>
                          <option value="recusada">Recusada</option>
                          <option value="expirada">Expirada</option>
                        </select>
                      </div>
                    </div>

                    <div>
                      <label className="block text-sm font-medium text-gray-700 mb-1">
                        Descrição
                      </label>
                      <textarea
                        value={selectedProposta.descricao || ''}
                        onChange={(e) => setSelectedProposta({ ...selectedProposta, descricao: e.target.value })}
                        disabled={!isEditing}
                        className="w-full px-3 py-3 border border-gray-300 rounded-md text-sm bg-white"
                        rows={5}
                        placeholder="Descrição da proposta"
                      />
                    </div>

                    <div>
                      <label className="block text-sm font-medium text-gray-700 mb-1">
                        Link da Proposta
                      </label>
                      <div className="flex gap-2">
                        <div className="flex-1 relative">
                          <span className="absolute left-3 top-1/2 -translate-y-1/2 text-sm text-gray-500">/proposta/</span>
                          <input
                            type="text"
                            value={selectedProposta.slug || ''}
                            onChange={(e) => {
                              const newSlug = e.target.value.toLowerCase().replace(/[^a-z0-9-]/g, '');
                              setSelectedProposta({ ...selectedProposta, slug: newSlug });
                              // Marcar que o slug foi editado manualmente
                              if (selectedProposta.id.startsWith('new-')) {
                                setSlugWasAutoGenerated(true); // Impede que seja sobrescrito automaticamente
                              }
                            }}
                            disabled={!isEditing}
                            className="w-full pl-24 pr-3 py-3 border border-gray-300 rounded-md text-sm bg-white"
                            placeholder="casal-joao-maria"
                          />
                        </div>
                        {selectedProposta.slug && !selectedProposta.id.startsWith('new-') && (
                          <>
                            <button
                              type="button"
                              onClick={() => {
                                const url = `${window.location.origin}/proposta/${selectedProposta.slug}`;
                                navigator.clipboard.writeText(url);
                                showToast('Link copiado!', 'success');
                              }}
                              className="px-3 py-2 text-sm border border-gray-300 rounded-md hover:bg-gray-50 flex items-center gap-2"
                              title="Copiar link"
                            >
                              <Copy className="size-4" />
                            </button>
                            <a
                              href={`/proposta/${selectedProposta.slug}`}
                              target="_blank"
                              rel="noopener noreferrer"
                              className="px-3 py-2 text-sm border border-gray-300 rounded-md hover:bg-gray-50 flex items-center gap-2"
                              title="Abrir em nova aba"
                            >
                              <ExternalLink className="size-4" />
                            </a>
                          </>
                        )}
                      </div>
                    </div>
                  </div>
                )}

                {/* Tab: Pagamento */}
                {activeTab === 'pagamento' && (
                  <div className="p-6 space-y-4">
                    <div>
                      <label className="block text-sm font-medium text-gray-700 mb-1">
                        Valor Total *
                      </label>
                      <input
                        type="text"
                        value={selectedProposta.valorTotal.toLocaleString('pt-BR')}
                        onChange={(e) => {
                          const value = e.target.value.replace(/\./g, '').replace(',', '.');
                          setSelectedProposta({ ...selectedProposta, valorTotal: parseFloat(value) || 0 });
                        }}
                        disabled={!isEditing}
                        className="w-full px-3 py-3 border border-gray-300 rounded-md text-sm bg-white"
                        placeholder="0"
                      />
                    </div>

                    <div>
                      <label className="block text-sm font-medium text-gray-700 mb-1">
                        Link de Pagamento (7 dias - 20% desconto)
                      </label>
                      <input
                        type="text"
                        value={selectedProposta.linkPagamento7Dias || ''}
                        onChange={(e) => setSelectedProposta({ ...selectedProposta, linkPagamento7Dias: e.target.value })}
                        disabled={!isEditing}
                        className="w-full px-3 py-3 border border-gray-300 rounded-md text-sm bg-white disabled:bg-gray-50 disabled:text-gray-500"
                        placeholder="Cole o link de pagamento aqui"
                      />
                    </div>

                    <div>
                      <label className="block text-sm font-medium text-gray-700 mb-1">
                        Link de Pagamento (21 dias - preço padrão)
                      </label>
                      <input
                        type="text"
                        value={selectedProposta.linkPagamento21Dias || ''}
                        onChange={(e) => setSelectedProposta({ ...selectedProposta, linkPagamento21Dias: e.target.value })}
                        disabled={!isEditing}
                        className="w-full px-3 py-3 border border-gray-300 rounded-md text-sm bg-white disabled:bg-gray-50 disabled:text-gray-500"
                        placeholder="Cole o link de pagamento aqui"
                      />
                    </div>
                  </div>
                )}

                {/* Botões de Ação */}
                {isEditing && (
                  <div className="flex items-center justify-end gap-3">
                    {!selectedProposta.id.startsWith('new-') && (
                      <button
                        onClick={() => handleDeleteClick(selectedProposta)}
                        className="btn-danger-xs-outline flex items-center gap-2"
                      >
                        <Trash2 className="w-4 h-4" />
                        Excluir Proposta
                      </button>
                    )}
                    <button
                      onClick={handleSaveProposta}
                      disabled={
                        isSaving || 
                        (!selectedProposta.id.startsWith('new-') && !hasChanges) ||
                        (selectedProposta.id.startsWith('new-') && (
                          !selectedProposta.clienteNome.trim() ||
                          !selectedProposta.dataEvento ||
                          !selectedProposta.localFesta?.trim() ||
                          selectedProposta.valorTotal <= 0
                        ))
                      }
                      className="btn-primary-xs flex items-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed"
                    >
                      <Check className="w-4 h-4" />
                      {isSaving ? 'Salvando...' : (selectedProposta.id.startsWith('new-') ? 'Criar Proposta' : 'Atualizar Proposta')}
                    </button>
                  </div>
                )}
              </div>
            </>
          )}
        </DialogContent>
      </Dialog>

      {/* Modal de Confirmação de Exclusão */}
      <Dialog open={isDeleteDialogOpen} onOpenChange={setIsDeleteDialogOpen}>
        <DialogContent className="max-w-md bg-[#F6EEE1]">
          <DialogHeader>
            <DialogTitle className="text-xl font-unbounded text-[#703535] text-left">
              Confirmar Exclusão
            </DialogTitle>
          </DialogHeader>
          {propostaToDelete && (
            <div className="space-y-4">
              <p className="text-sm text-gray-700">
                Tem certeza que deseja excluir a proposta de <strong>{propostaToDelete.clienteNome}</strong>?
              </p>
              <p className="text-sm text-gray-600">
                Esta ação não pode ser desfeita.
              </p>
              <div className="flex items-center justify-end gap-3 mt-6">
                <button
                  onClick={handleCancelDelete}
                  disabled={isDeleting}
                  className="btn-secondary-xs-outline"
                >
                  Cancelar
                </button>
                <button
                  onClick={handleConfirmDelete}
                  disabled={isDeleting}
                  className="btn-danger-xs flex items-center gap-2"
                >
                  <Trash2 className="size-4" />
                  {isDeleting ? 'Excluindo...' : 'Excluir'}
                </button>
              </div>
            </div>
          )}
        </DialogContent>
      </Dialog>
    </div>
  );
}
