export { default as HeroSection } from './HeroSection'
export { default as CalculatorSection } from './CalculatorSection'
export { HowToSection } from './HowToSection'
export { default as PainSection } from './PainSection'
export { default as PricingSection } from './PricingSection'
export { default as FAQSection } from './FAQSection'
export { default as AboutSection } from './AboutSection'
export { default as CronogramaSection } from './CronogramaSection'
export { default as DisclaimerSection } from './DisclaimerSection'
export { ConteudoSection } from './ConteudoSection'
export { default as SecondSection } from './SecondSection'